version: '3.9'
services:
  app:
    platform: linux/amd64
    image: nxtdkr
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
        - /app/public
    ports:
      - "3000:3000"